apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: appgestion
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api

  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
